spring:
  application:
    name: multitenantDemo


  datasource:
    url: 'jdbc:postgresql://localhost:5432/mutitenancy'
    username: postgres
    password: password
    driver-class: org.postgresql.Driver


  flyway:
    enabled: true
    locations: classpath:db/migration
    password: password
    user: postgres


  jpa:
    properties:
      hibernate:
        ddl-auto: validate




